#!/usr/bin/env python3
"""
Script to update project descriptions in HTML files based on CSV data.
"""

import os
import re
from pathlib import Path

# CSV data provided by user
DESCRIPTIONS = {
    "Dean-Hunt-Olof-Mathe": "The stand off Elon and Zuck always wanted, and you're invited.",
    "Kelly-Neuner-Termie-Gavan-Wilhite-Dean-Hunt-Olof-Mathe-Ian-Wallace-Termie": "In the first of the Four World Wars, nostalgia was a capital offense and your sergeant was obligated to shoot you for showing it. We take a softer approach in 2172. This piece puts the focus back on forgotten milestones: the Second Orca-Human Peace Accords; a Final Natural Birth; the Universal Adoption of Brain Implants, the Last Successfully Plugged Volcano; and of course that change to the Flordia law requiring all bankrupt billionaires to occupy any remaining starships as their primary residence, freeing up valuable beach space for Orcachildren. Did we miss something? We welcome you to fix any gaps at https://reposter.studio/generate",
    "Julia-Daser-Criplishus": "Who is our city built for?\nOur art installation, Structural Integrity, points attention to the changes forced on our community by exaggerating the duality of public accommodations. One seat is inviting and comfortable, while its antithetical mate features painful spikes and other repelling technologies currently employed against the unhoused population. The emotional and tactile impact of Structural Integrity seeks to foster fresh discussions by exposing the juxtaposition of pain and pleasure in public space.",
    "Quin-Kennedy-Dean-Hunt-Olof-Mathe": "\"I contain multitudes.\" \"I am nobdy, who are you?\" American poetry starts with an extrovert and an introvert saying the same thing: we're everything; we're nothing. Modern trauma therapies like IFS also teach us what we've always known about the self: we are what we leave behind. Living has always been grief work.\n\nThousands of pilgrims walk the Camino de Santiago across Spain every year. They're told to bring a stone from home with them, to carry it five hundred miles. They don't yet know the point is to leave it behind, early, under an iron cross in the countryside, adding to a meters-high mountain of human grief and loss. The point is to grieve together, and to keep going.\n\nLiving has always been choosing what to leave. Text us what you want let go of and watch it fall from the throne: +1 415-598-5687",
    "Fletcher-Bach-Vidya-Giri-Anna-Zhang-Andrew-Johnson-Tatjana-Kudinova": "The terms of service of major tech platforms give platform owners significant power, binding users to complex agreements that grant broad control over their data and content, with limited negotiation or consent. Users lack opt-out choices and remedies for breaches, revealing a system that prioritizes owner control over user rights. If the tech company's terms of service are a declaration of a particular power dynamic, then On Our Terms is a collaborative critical response, inviting tech companies to adopt terms defined by the user community.",
    "Termie-Quin-Kennedy": "Your employer does not love you.\nThey keep you in the dark to deny you power.\nYou have the right to discuss your wages.\nIt helps you, your coworkers, and us all.\nInformed wage negotiations can net you millions over a\nlifetime of pay.\n\nDo not remain silent.",
    "Josette-Seitz-Ian-Wallace-Lee-Butterman": "Within the delta is an invitation to co-imagine desired futures. The viewer approaches an animation of prior participants' hopes and dreams, and is invited to express a desire for the future, and a visual prompt for this desire is generated by an open source LLM, and this visual prompt is animated with Stable Diffusion, and added to the loop that the next viewer will see.",
    "Cassandra-Scarpa-Emma-Liddell-Skye-Battles": "This interactive installation playfully confronts the hidden power dynamics embedded within everyday technology. By amplifying the absurdity of wealth worship, we expose the invisible mechanisms of control that dictate so much of our lives. Viewers are encouraged to question the legitimacy of these power structures and envision ways to reclaim agency in a world built unjustly on exploitation and the centralization of unearned power.\nParticipants are asked to bow down and praise modern-day kings, exposing the absurdity of our continued reverence for a new form of unjust, technologically-empowered nobility.",
    "Caroline-Hermans-Jesse-Buddington": "A shrine to Elizabeth Holmes",
    "Lyra-Levin-Jesse-Buddington": "Join us for a five-minute, guided meditation to reclaim your power over time. Our practice progressively removes the supports of the attention economy throne, clearing space for you to exist more fully in its wake.",
    "Koi-Ren-Sang-Leigh-Joey-Verbeke-Jess-Kim-Jeffrey-Hawkins": "In vetro / In vivo - Trial #1:\n\"Dethroning\" is the radical act of being in community and holding empathy for each other. Through being in community, we can work to disengage and \"dethrone\" systems of oppression and power.\n\n\"Trial 1\" navigates the delicate balance between agency and absence, as even in moments of unconscious inaction, our essence is woven into unfolding realms. It muses on the unseen forces that sway us between control and compliance, inviting reflection on our ephemeral entanglement with these vast, intangible domains.\n\nIn vivo / In vetro - Trial #2:\n\"Dethroning\" is the radical act of being in community and holding empathy for each other. Through being in community, we can work to disengage and \"dethrone\" systems of oppression and power.\n\nIn \"Trial 2\" communal engagement and surveillance grow a embryonic cell culture as a medium of collective evolution. This trial explores the juxtaposition of surveillance and extraction, inviting outrospection on the state of being controlled as well as influencing the system, endeavoring to capture our ambiguous relationship with collective change.",
    "Amy-Lee-Ash-Herr-Jesse-Buddington-Lyra-Levin-Natalia-Ricalde-ThePostFuturist": "The mob is fickle. Win admiration or perish. #NvidiaYolo42069 #DumbMoneyVisionPro\n\nYour attention is your power. Put yourself on the market and compete to acquire attention from the audience.\n\nIn \"Pump It Up\", we explore the struggle of \"new money\" (Red) up-and-coming companies versus \"old money\" (White) entrenched organizations. Both the \"new\" and \"old\" battle against each other to maintain or acquire more power.\n\nBattle against your competitor and compete for attention. Increase your own stock price by convincing the mob to raise their arms for you.\n\nCan you increase your own equity and dethrone your opponent?",
    "Danielle-Baskin-Colin-Sullivan-Way-Shong-Ryan-Alexander": "Question everything. Trust us.",
    "Danielle-Baskin": "There's a trend of fencing off city benches to restrict public sitting. Here's a bench at 24th St. & Mission. Call the Bench Reservation System hotline at (415) 212-7762 to see if you qualify to sit.",
    "Yuting-Wang-Cheng-Xu-Eddie-Contreras-Chloe-Li-": "The world as we perceive it is inherently shaped by our individual preconceptions. This door - a symbol of transition and opportunity - opens not to a new physical space, but to various scales and interpretations of the same composition. What is real and which version of reality will we choose to step into?",
    "Lee-Butterman": "Diffusion Local Time is an exploration of the surrealism of generative AI. We juxtapose the pareidolia of seeing faces in clouds or seeing desert mirages, with the quotidian digital clock, all running locally on a personal computer. The frequency of visual updates (every few seconds) running on a consumer device challenges the inherent power dynamic of requiring rented surveilled machines. The image prompt can be customized. Here, we display a traditional California landscape as the backdrop."
}

PROJECTS_DIR = Path("projects")

def escape_html(text):
    """Escape HTML special characters."""
    return (text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;"))

def update_file(filename, new_description):
    """Update description in an HTML file."""
    filepath = PROJECTS_DIR / f"{filename}.html"
    
    if not filepath.exists():
        print(f"⚠️  File not found: {filepath}")
        return False
    
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Escape HTML for meta tag (single line, no newlines)
    meta_description = new_description.replace('\n', ' ').strip()
    meta_description_escaped = escape_html(meta_description)
    
    # For the <p> tag, we can preserve newlines as <br/> tags
    # But first, let's see what the current format is
    # We'll replace the content between <p> and </p> in the project-description section
    
    # Update og:description meta tag
    og_pattern = r'(<meta\s+property=["\']og:description["\']\s+content=["\'])([^"\']*)(["\']\s*/>)'
    if re.search(og_pattern, content):
        content = re.sub(og_pattern, r'\1' + meta_description_escaped + r'\3', content)
    else:
        print(f"⚠️  Could not find og:description in {filename}")
    
    # Update <p> tag in project-description section
    # Find the <p> tag that comes after the "Dethrone" link and before "Contributors"
    # Try multiple patterns to find the <p> tag
    p_patterns = [
        r'(<div class="basic-colfax black-link">.*?</div>\s*)(<p>)(.*?)(</p>)',
        r'(<div class="one-third column" id="project-description">.*?<div class="basic-colfax black-link">.*?</div>\s*)(<p>)(.*?)(</p>)',
        r'(<div id="project-description">.*?<div class="basic-colfax black-link">.*?</div>\s*)(<p>)(.*?)(</p>)',
    ]
    
    p_updated = False
    for p_pattern in p_patterns:
        match = re.search(p_pattern, content, re.DOTALL)
        if match:
            # Convert newlines to <br/> tags for HTML display
            p_description = new_description.replace('\n', '<br/>\n')
            # Escape HTML but preserve <br/> tags
            p_description_escaped = escape_html(p_description)
            p_description_escaped = p_description_escaped.replace('&lt;br/&gt;', '<br/>')
            content = re.sub(
                p_pattern,
                r'\1\2' + p_description_escaped + r'\4',
                content,
                flags=re.DOTALL
            )
            p_updated = True
            break
    
    if not p_updated:
        print(f"⚠️  Could not find <p> tag in project-description for {filename}")
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return True

def main():
    """Main function to update all project descriptions."""
    print("=" * 60)
    print("Updating Project Descriptions")
    print("=" * 60)
    print()
    
    updated = 0
    not_found = []
    
    for filename, description in DESCRIPTIONS.items():
        print(f"Processing: {filename}")
        if update_file(filename, description):
            updated += 1
            print(f"  ✓ Updated")
        else:
            not_found.append(filename)
        print()
    
    print("=" * 60)
    print(f"Summary: {updated} files updated")
    if not_found:
        print(f"Files not found: {', '.join(not_found)}")
    print("=" * 60)

if __name__ == "__main__":
    main()

